### ISSUE TITLE
Special Event Permit Application

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#212]
Online: https://www.boston.gov/parks-special-event-permit-application
PDF: 
[boston_parks_special_event_application.pdf](https://github.com/joshuagee/Forms/files/397891/boston_parks_special_event_application.pdf)
Contact: Paul McCaffrey <paul.mccaffrey@boston.gov>

**Comment by jduffy2001** [comment]
Added to the transactions page.
