### ISSUE TITLE
Design Review Construction Near Parks

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#215]
Online: https://www.boston.gov/design-review-construction-near-parks
PDF: [application_information_for_commission_review_tcm3-53239.pdf](https://github.com/joshuagee/Forms/files/397900/application_information_for_commission_review_tcm3-53239.pdf)
Contact: ryan.woods@boston.gov (617) 961-3015

**Comment by jduffy2001** [comment]
Added to transactions page.
