### ISSUE TITLE
Boston EMS Special Event Permit Application

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#23]
PDF:
[Boston EMS Permit_tcm3-24421.pdf](https://github.com/joshuagee/Forms/files/394391/Boston.EMS.Permit_tcm3-24421.pdf)

Contact:
"Segal, Laura" <segal@bostonems.org>,
"Curran, Erin" <curran@bostonems.org>

**Comment by joshuagee** [comment]
SeamlessDocs:

https://boston.seamlessdocs.com/f/C3eep

**Comment by joshuagee** [comment]
This is held up by a needed fix to how sidebar components stack. They want custom contact info and now it looks a bit wonky.

**Comment by jduffy2001** [comment]
Added to transactions page.
