### ISSUE TITLE
Report an AED Location

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#24]
Seamlessdoc Created:

https://boston.seamlessdocs.com/f/auQ5w7

Contacts:

"Segal, Laura" <segal@bostonems.org>,
"Curran, Erin" <curran@bostonems.org>

**Comment by joshuagee** [comment]
This is held up by a needed fix to how sidebar components stack. They want custom contact info and now it looks a bit wonky.

**Comment by joshuagee** [comment]
Posted anyway

**Comment by jduffy2001** [comment]
Added to the transactions page.
