### ISSUE TITLE
EMS Community Event Request

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#301]
PDF: In a folder on Josh's desk.

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/K7z5hG

**Comment by joshuagee** [comment]
https://www.boston.gov/ems-community-eventtraining-request

**Comment by joshuagee** [comment]
https://edit.boston.gov/ems-community-eventtraining-request-form

**Comment by joshuagee** [comment]
Splitting this into two forms.

    Title: Request Boston EMS Participation at Event
·         All existing fields except, two sections pertaining to training
·         Under event details, include:

o   Estimated number of participants (free text field)

o   Briefly describe how you would like Boston EMS to participate
·         Change that last section title to “EMS Informational Topics” (please select particular topics you would like Boston EMS to address)
·         Change ‘Informational Presentations’ to ‘Informational Topics’
·         Under that section, add ‘Hands-Only CPR’
·         Also, can you change the ‘Mass Orders…’ to the full name (“Massachusetts…”) with the first letters of the word capitalized, and  the last check box to ‘Emergency Preparedness for Seniors’ (there wasn’t an ‘s’ at the end of seniors
·         Make all fields mandatory except the informational topics and the additional information box at the end.

 
For the Training Request (As a link off of step three of this page: https://www.boston.gov/departments/emergency-medical-services/cpr-training
·         Title: Boston EMS CPR Training Request
·         Remove event detail section
·         Remove Informational presentations
·         Add ‘Number of Participants’
·         Make all fields mandatory except the last section, which should be called: ‘What Boston EMS Training Are You Interested In?’, and the Additional Information box

**Comment by joshuagee** [comment]
CPR request has been moved to #307

**Comment by jduffy2001** [comment]
Added to the transactions page.
