### ISSUE TITLE
My Brother's Keeper Grant Application

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#306]
Contact: Conan Harris <conan.harris@boston.gov>

Details: 

Grant Period: 

The City of Boston, My Brothers Keeper Mini Grant Program is intended to provide support and engagement for young people of color, primarily boys, in the City of Boston.The goal of the mini grants is to expand opportunity and create pipelines for young people.to be enriched in positive programming. The purpose of My Brothers Keeper Mini Grant Program is to support mentorship, creative discussions and activities by nonprofits and organizations who will direct his/her future efforts toward the six milestones: 1.getting a healthy start and entering school ready to learn, 2.reading at grade level by third grade, 3.graduating from high school and ready for college and career, 4.completing post secondary education or training, 5.successfully entering the workplace 6.keeping kids on track and giving them second chances through valuable experience toward that end.

My Brother's Keeper is a national initiative that addresses persistent opportunity gaps faced by young men of color. It aims to ensure that all young people can reach their full potential. Our city is building an engaged community around the vision and mission of My Brother’s Keeper and the City of Boston wants your help.

     Grant Awards range from $1,000-$7,000
              Deadline for Receipt of Proposals: 

Arrange Mini-Grant proposals in the following order:

1. Cover Sheet/Routing Sheet
2. Proposal Title
3. Project Summary (limited to one page)
4. Project Narrative (limited to one page)
5. Timeline (Action Plan) (limited to one page)
6. Literature Cited
7. Budget
8. Budget Justification
9. Previous Internal and External Grants Submitted and/or Received ( if applicable)

**Comment by joshuagee** [comment]
SeamlessDoc Created: https://seam.ly/ssUFfr

**Comment by joshuagee** [comment]
live at https://www.boston.gov/my-brothers-keeper-grant-application

**Comment by joshuagee** [comment]
script code: 

9dd7ca3b1bb3756ca36c6f0a05a1d2aa

**Comment by joshuagee** [comment]
Sitting in draft mode, waiting for August 22 announcement to make live.

**Comment by jduffy2001** [comment]
Added to the transactions page.
