### ISSUE TITLE
CPR Training Request

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#307]
Split from 
https://boston.seamlessdocs.com/f/K7z5hG

#301 

I just spoke to Felicia Robinson, our community initiatives lead and she was wondering if there is any way we can separate out event requests and trainings? She just got a request and they pretty much requested everything. When we talked through what she wanted we realized, the challenge we were facing was that these are really two different types of requests, one is to have us participate in a community event and the other is asking us to provide a training. For community events, we will sometimes do brief hands-only CPR trainings at a table, but it isn’t a structured training.  Sorry to request all these changes, sometimes it isn’t until requests come in that we realize there is a better way.
 
The Event Request (as a link off of the ‘More EMS Information’ home page section, although we would want to retitle that section link to “Request Boston EMS Participation at Event” and the subtext to the right would have to read “Boston EMS provides community event ambulance tours, presentations and informational tables

For the Training Request (As a link off of step three of this page: https://www.boston.gov/departments/emergency-medical-services/cpr-training
·         Title: Boston EMS CPR Training Request
·         Remove event detail section
·         Remove Informational presentations
·         Add ‘Number of Participants’
·         Make all fields mandatory except the last section, which should be called: ‘What Boston EMS Training Are You Interested In?’, and the Additional Information box

·         Title: Request Boston EMS Participation at Event
·         All existing fields except, two sections pertaining to training
·         Under event details, include:
o   Estimated number of participants (free text field)
o   Briefly describe how you would like Boston EMS to participate
·         Change that last section title to “EMS Informational Topics” (please select particular topics you would like Boston EMS to address)
·         Change ‘Informational Presentations’ to ‘Informational Topics’
·         Under that section, add ‘Hands-Only CPR’
·         Also, can you change the ‘Mass Orders…’ to the full name (“Massachusetts…”) with the first letters of the word capitalized, and  the last check box to ‘Emergency Preparedness for Seniors’ (there wasn’t an ‘s’ at the end of seniors
·         Make all fields mandatory except the informational topics and the additional information box at the end.

Contact: 	Segal, Laura <Segal@bostonems.org>
PDF: Folder on my desk (actually a printout of a previous folder)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/VJB9Ow

**Comment by jduffy2001** [comment]
Added the online request form to the transactions page.
