### ISSUE TITLE
Equipment Request Form

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#317]
PDF: [EQUIPMENT REQUEST FORM.docx](https://github.com/joshuagee/Forms/files/457416/EQUIPMENT.REQUEST.FORM.docx)

Contact: ryan.woods@boston.gov

**Comment by joshuagee** [comment]
https://seam.ly/0ZFFcX

**Comment by joshuagee** [comment]
![signoff](https://cloud.githubusercontent.com/assets/20726937/18326102/3f23d76a-7512-11e6-9848-18ed29a95b5a.PNG)

**Comment by joshuagee** [comment]
https://hub.boston.gov/parks-and-recreation-equipment-request-form

**Comment by reillyzlab** [comment]
@joshuagee is there a brief description of this that I can display with the link? one of biggest things we're trying to do on Hub is provide context (where we can)

**Comment by reillyzlab** [comment]
@joshuagee just FYI 

https://hub.boston.gov/departments/parks-and-recreation
