### ISSUE TITLE
ISD Public Record Request Form

### ISSUE THREAD

**Issue by joshuagee** [joshuagee/Forms#43]
PDF:
[Public Records Request Form final 3 10 final_tcm3-17878 (2).pdf](https://github.com/joshuagee/Forms/files/394618/Public.Records.Request.Form.final.3.10.final_tcm3-17878.2.pdf)

Web form:
https://www.boston.gov/inspectional-services-public-records-request-form

**Comment by joshuagee** [comment]
Need to change the address on the pdf before it can be posted publicly.

**Comment by jduffy2001** [comment]
Added to the transactions page.
